version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.0
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
    - 1.11.1
  - dependency-name: focus-trap
    versions:
    - 6.3.0
  - dependency-name: uikit
    versions:
    - 3.6.14
    - 3.6.15
    - 3.6.16
    - 3.6.17
    - 3.6.18
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.8
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: lint-staged
    versions:
    - 10.5.3
    - 10.5.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: ember-composable-helpers
    versions:
    - 4.4.1
